---
logo:
  image_url: "/uploads/images/8fb5c90629016f0c26d86a8de4fe79ac.jpg"
  redirect_to: "/"
banner_one:
  image_url: "/uploads/images/ff48ff2a48b3d9aa4a296a9613e745b9.jpeg"
  redirect_to: https://github.com/carrierwaveuploader/carrierwave
banner_two:
  image_url: "/uploads/images/5ece241793931424d6b3f537949fe57a.png"
  redirect_to: https://github.com/carrierwaveuploader/carrierwave
banner_three:
  image_url: "/uploads/images/7b0b6c252f979943f63d6e22ace98031.png"
  redirect_to: https://github.com/carrierwaveuploader/carrierwave
