---
banner_one:
  image_url: http://static.segmentfault.com/page/img/avatar/fen.c0d35a56.png
  redirect_to: ''
banner_two:
  image_url: http://static.segmentfault.com/page/img/avatar/fen.c0d35a56.png
  redirect_to: ''
banner_three:
  image_url: ''
  redirect_to: ''
